services:
  redpanda:
    image: redpandadata/redpanda:v24.1.6
    command: >
      redpanda start --overprovisioned --smp 1 --memory 512M --reserve-memory 0M
      --node-id 0 --check=false --kafka-addr INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:19092
      --advertise-kafka-addr INTERNAL://redpanda:9092,EXTERNAL://localhost:19092
    ports:
      - "19092:19092"
      - "9644:9644"

  transaction-service:
    build:
      context: .
      dockerfile: services/transaction-service/Dockerfile
    environment:
      - PORT=3000
      - KAFKA_BROKERS=redpanda:9092
    depends_on:
      - redpanda
    ports:
      - "3000:3000"

  anti-fraud-service:
    build:
      context: .
      dockerfile: services/anti-fraud-service/Dockerfile
    environment:
      - KAFKA_BROKERS=redpanda:9092
    depends_on:
      - redpanda
